# TO DO

services: 
  server:
    build: ./backend
    container_name: "rollify_backend"
    ports:
      - "80:80"
    networks:
      - rollify-net
  bbdd:
    image: mariadb:10.5.6
    container_name: "rollify_bbdd"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mybbdd
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
    networks:
      - rollify-net

networks:
  rollify-net:
    name: rollify_network
