version: '2'

services: 
  bbdd:
    image: mariadb:10.5.6
    container_name: "rollify_bbdd"
    env_file:
    - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_ENV}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - "./database/mysql_data:/var/lib/mysql"
      - "./database/init.d:/docker-entrypoint-initdb.d"
    ports:
      - ${DATABASE_PORT_MAP}
    networks:
      rollify-net:
        ipv4_address: 172.16.238.3 
        ipv6_address: "2001:3984:3989::3"

  server:
    build: ./
    container_name: "rollify_backend"
    env_file:
    - .env
    ports:
      - ${SERVER_PORT_MAP}
    depends_on:
      - bbdd
    command: sh -c "/wait && /app/main"
    environment:
      - WAIT_HOSTS=rollify_bbdd:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=60
    networks:
      rollify-net:
        ipv4_address: 172.16.238.2 
        ipv6_address: "2001:3984:3989::2"

networks:
  rollify-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"
