# TO DO

services: 
  server:
    build: ./backend
    container_name: "storyx_backend"
    ports:
      - "80:80"
    networks:
      - backend
  bbdd:
    image: mariadb:10.5.6
    container_name: "storyx_bbdd"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mybbdd
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
    networks:
      - backend

networks:
  backend:
    name: storyx_network
