# TO DO

services: 
  bbdd:
    image: mariadb:10.5.6
    container_name: "rollify_bbdd"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rollify
      MYSQL_USER: rollify
      MYSQL_PASSWORD: password
    volumes:
      - "./database/mysql_data:/var/lib/mysql"
      - "./database/init.d:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - rollify-net
  server:
    build: ./
    container_name: "rollify_backend"
    ports:
      - "8080:8080"
    networks:
      - rollify-net

networks:
  rollify-net:
    name: rollify_backend-net
