# TO DO

services: 
  server:
    build: ./
    container_name: "rollify_backend"
    ports:
      - "10000:10000"
    networks:
      - rollify-net
  bbdd:
    image: mariadb:10.5.6
    container_name: "rollify_bbdd"
    environment:
      MYSQL_ROOT_PASSWORD: 82y!RQ!^3e6@7$B4Q3*$
      MYSQL_DATABASE: rollify
      MYSQL_USER: rollify
      MYSQL_PASSWORD: 89Xu!%3r!7kE*A
    networks:
      - rollify-net

networks:
  rollify-net:
    name: rollify_backend-net
